//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначена.
        /// </summary>
        public static string LIST_STATUS_0 {
            get {
                return ResourceManager.GetString("LIST_STATUS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется.
        /// </summary>
        public static string LIST_STATUS_1 {
            get {
                return ResourceManager.GetString("LIST_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приостановлена.
        /// </summary>
        public static string LIST_STATUS_2 {
            get {
                return ResourceManager.GetString("LIST_STATUS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершена.
        /// </summary>
        public static string LIST_STATUS_3 {
            get {
                return ResourceManager.GetString("LIST_STATUS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление подзадач к завершённым задачам запрещено!.
        /// </summary>
        public static string MODEL_EXC_AddingSubtasksToCompletedTasksIsProhibited {
            get {
                return ResourceManager.GetString("MODEL_EXC_AddingSubtasksToCompletedTasksIsProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение завершённых задач запрещено!.
        /// </summary>
        public static string MODEL_EXC_ChangingCompletedTasksIsProhibited {
            get {
                return ResourceManager.GetString("MODEL_EXC_ChangingCompletedTasksIsProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрещено редактировать выполненную задачу!.
        /// </summary>
        public static string MODEL_EXC_EditingCompletedTaskIsProhibited {
            get {
                return ResourceManager.GetString("MODEL_EXC_EditingCompletedTaskIsProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в модуле &quot;Model&quot;..
        /// </summary>
        public static string MODEL_EXC_HEADER {
            get {
                return ResourceManager.GetString("MODEL_EXC_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция удаления отклонена! Необходимо удалить все подзадачи!.
        /// </summary>
        public static string MODEL_EXC_NecessaryToDeleteSubtasks {
            get {
                return ResourceManager.GetString("MODEL_EXC_NecessaryToDeleteSubtasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача не может быть выполнена! Есть подзадачи, не принятые к выполнению!.
        /// </summary>
        public static string MODEL_EXC_SubtasksAreNotAccepted {
            get {
                return ResourceManager.GetString("MODEL_EXC_SubtasksAreNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция не определена!.
        /// </summary>
        public static string MODEL_MSG_OperationNotDefined {
            get {
                return ResourceManager.GetString("MODEL_MSG_OperationNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача успешно добавлена..
        /// </summary>
        public static string MODEL_MSG_TaskSuccessfullyAdded {
            get {
                return ResourceManager.GetString("MODEL_MSG_TaskSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача успешно изменена..
        /// </summary>
        public static string MODEL_MSG_TaskSuccessfullyChanged {
            get {
                return ResourceManager.GetString("MODEL_MSG_TaskSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача успешно удалена..
        /// </summary>
        public static string MODEL_MSG_TaskSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("MODEL_MSG_TaskSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача успешно сохранена..
        /// </summary>
        public static string MODEL_MSG_TaskSuccessfullySaved {
            get {
                return ResourceManager.GetString("MODEL_MSG_TaskSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление подзадач к завершённым задачам запрещено!.
        /// </summary>
        public static string VM_EXC_AddingSubtasksToCompletedTasksIsProhibited {
            get {
                return ResourceManager.GetString("VM_EXC_AddingSubtasksToCompletedTasksIsProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение завершённых задач запрещено!.
        /// </summary>
        public static string VM_EXC_ChangingCompletedTasksIsProhibited {
            get {
                return ResourceManager.GetString("VM_EXC_ChangingCompletedTasksIsProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершать задачу со статусом НАЗНАЧЕНА запрещено!.
        /// </summary>
        public static string VM_EXC_ForbiddenToCompleteAssignedTask {
            get {
                return ResourceManager.GetString("VM_EXC_ForbiddenToCompleteAssignedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в модуле &quot;ViewModel&quot;..
        /// </summary>
        public static string VM_EXC_HEADER {
            get {
                return ResourceManager.GetString("VM_EXC_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер задач.
        /// </summary>
        public static string WND_MAIN_CAPTION {
            get {
                return ResourceManager.GetString("WND_MAIN_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершена:.
        /// </summary>
        public static string WND_MAIN_END {
            get {
                return ResourceManager.GetString("WND_MAIN_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факт. часов:.
        /// </summary>
        public static string WND_MAIN_FACT {
            get {
                return ResourceManager.GetString("WND_MAIN_FACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to План. часов:.
        /// </summary>
        public static string WND_MAIN_PLAN {
            get {
                return ResourceManager.GetString("WND_MAIN_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрац.: .
        /// </summary>
        public static string WND_MAIN_REGS {
            get {
                return ResourceManager.GetString("WND_MAIN_REGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string WND_MAIN_STR_UNITS {
            get {
                return ResourceManager.GetString("WND_MAIN_STR_UNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + подазадачи:.
        /// </summary>
        public static string WND_MAIN_SUBTASK {
            get {
                return ResourceManager.GetString("WND_MAIN_SUBTASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить задачу.
        /// </summary>
        public static string WND_MAIN_TIP_00 {
            get {
                return ResourceManager.GetString("WND_MAIN_TIP_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принять задачу к выполнению.
        /// </summary>
        public static string WND_MAIN_TIP_01 {
            get {
                return ResourceManager.GetString("WND_MAIN_TIP_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приостановить выполнение задачи.
        /// </summary>
        public static string WND_MAIN_TIP_02 {
            get {
                return ResourceManager.GetString("WND_MAIN_TIP_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить задачу.
        /// </summary>
        public static string WND_MAIN_TIP_03 {
            get {
                return ResourceManager.GetString("WND_MAIN_TIP_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить задач.
        /// </summary>
        public static string WND_MAIN_TIP_04 {
            get {
                return ResourceManager.GetString("WND_MAIN_TIP_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать задачу.
        /// </summary>
        public static string WND_MAIN_TIP_05 {
            get {
                return ResourceManager.GetString("WND_MAIN_TIP_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить подзадачу.
        /// </summary>
        public static string WND_MAIN_TIP_06 {
            get {
                return ResourceManager.GetString("WND_MAIN_TIP_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string WND_MESSAGE_CAPTION {
            get {
                return ResourceManager.GetString("WND_MESSAGE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        public static string WND_MESSAGE_OK {
            get {
                return ResourceManager.GetString("WND_MESSAGE_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Праметры задачи.
        /// </summary>
        public static string WND_TASK_CAPTION {
            get {
                return ResourceManager.GetString("WND_TASK_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string WND_TASK_DESC {
            get {
                return ResourceManager.GetString("WND_TASK_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнители.
        /// </summary>
        public static string WND_TASK_EXEC {
            get {
                return ResourceManager.GetString("WND_TASK_EXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача.
        /// </summary>
        public static string WND_TASK_NAME {
            get {
                return ResourceManager.GetString("WND_TASK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плановая трудоёмкость в часах.
        /// </summary>
        public static string WND_TASK_PLAN {
            get {
                return ResourceManager.GetString("WND_TASK_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string WND_TASK_SAVE {
            get {
                return ResourceManager.GetString("WND_TASK_SAVE", resourceCulture);
            }
        }
    }
}
